services:
  database:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: auth-strategies
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10m
      timeout: 3s
      start_period: 10s
      start_interval: 5s
      retries: 3

  server:
    depends_on:
      database:
        condition: service_healthy
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: database

volumes:
  db-volume:
