// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type UserAccount struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}
