// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         int32
	UserID     uuid.UUID
	PublicID   string
	SecretHash []byte
	SecretSalt []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type PasswordAuth struct {
	ID     int32
	UserID uuid.UUID
	PwHash []byte
	PwSalt []byte
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type UserAccount struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}
