// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getPasswordAuth = `-- name: GetPasswordAuth :one
SELECT ua.id, pa.pw_hash, pa.pw_salt
FROM user_account ua
JOIN password_auth pa ON pa.user_id = ua.id
WHERE ua.email=$1
`

type GetPasswordAuthRow struct {
	ID     uuid.UUID
	PwHash []byte
	PwSalt []byte
}

func (q *Queries) GetPasswordAuth(ctx context.Context, email string) (GetPasswordAuthRow, error) {
	row := q.db.QueryRow(ctx, getPasswordAuth, email)
	var i GetPasswordAuthRow
	err := row.Scan(&i.ID, &i.PwHash, &i.PwSalt)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT first_name, last_name FROM user_account WHERE id=$1
`

type GetUserInfoRow struct {
	FirstName string
	LastName  string
}

func (q *Queries) GetUserInfo(ctx context.Context, id uuid.UUID) (GetUserInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserInfo, id)
	var i GetUserInfoRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}
