// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT first_name, last_name FROM user_account WHERE id=$1
`

type GetUserInfoRow struct {
	FirstName string
	LastName  string
}

func (q *Queries) GetUserInfo(ctx context.Context, id uuid.UUID) (GetUserInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserInfo, id)
	var i GetUserInfoRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}
